# Generated by Django 4.0.3 on 2022-03-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('orderId', models.CharField(max_length=100)),
                ('order_amount', models.BigIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
