# Generated by Django 4.0.3 on 2022-03-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodId', models.AutoField(primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=100)),
                ('foodType', models.CharField(max_length=20)),
                ('foodPrice', models.FloatField()),
                ('foodDescription', models.TextField()),
                ('foodImage', models.ImageField(default='No-Image.png', upload_to='foodimages/')),
            ],
        ),
    ]
